### ISSUE TITLE
训练模式

### ISSUE THREAD

**Issue by GodeWithWind** [songquanpeng/pytorch-template#1]
parser.add_argument('--mode', type=str, default='train', choices=['train', 'eval', 'sample'])
请问这里的sample模式是什么呢

**Comment by songquanpeng** [comment]
`mode` 参数用于设置运行模式，`sample` 是取样模式，对于生成性质的模型有用，例如 GAN 的训练。

**Comment by GodeWithWind** [comment]
好的，感谢
